from typing import Literal, Set, cast

EmailCommunicationCategory = Literal[
    "Account ownership information updated",
    "Account Statement",
    "Appointment Cancellation",
    "Appointment Confirmation",
    "Appointment Reminder",
    "Auth Code",
    "Bulk Email",
    "Cancelled appointment notification",
    "Card automatically updated notification",
    "Card expiring notification",
    "Completed Patient Form",
    "Data export complete notification",
    "Email OTP code",
    "Invoice",
    "Letter",
    "Mailchimp integration disconnected",
    "Memo",
    "New user",
    "Online payment request",
    "Password changed",
    "Patient Form",
    "Patient Reply Forwarded",
    "Payment Receipt",
    "Practitioner Appointment Notification",
    "Referred user bonus notification",
    "Referred user signed up",
    "Referring user bonus notification",
    "Reply from Patient",
    "Reply from Practitioner",
    "Reset password instructions",
    "SMS credit purchase failed",
    "SMS credit purchase receipt",
    "SMS credit purchase reminder",
    "SMS credit purchase requires confirmation",
    "SMS Message",
    "Stripe receipt",
    "Subscription payment failure",
    "Today's appointments for practitioner",
    "Trial ending reminder",
    "Trial payment failure",
    "Unlock instructions",
    "Upcoming appointments",
    "Upcoming yearly payment alert",
    "User email changed",
    "User email confirmation instructions",
    "Xero OAuth error",
    "Xero sync error notification",
]

EMAIL_COMMUNICATION_CATEGORY_VALUES: Set[EmailCommunicationCategory] = {
    "Account ownership information updated",
    "Account Statement",
    "Appointment Cancellation",
    "Appointment Confirmation",
    "Appointment Reminder",
    "Auth Code",
    "Bulk Email",
    "Cancelled appointment notification",
    "Card automatically updated notification",
    "Card expiring notification",
    "Completed Patient Form",
    "Data export complete notification",
    "Email OTP code",
    "Invoice",
    "Letter",
    "Mailchimp integration disconnected",
    "Memo",
    "New user",
    "Online payment request",
    "Password changed",
    "Patient Form",
    "Patient Reply Forwarded",
    "Payment Receipt",
    "Practitioner Appointment Notification",
    "Referred user bonus notification",
    "Referred user signed up",
    "Referring user bonus notification",
    "Reply from Patient",
    "Reply from Practitioner",
    "Reset password instructions",
    "SMS credit purchase failed",
    "SMS credit purchase receipt",
    "SMS credit purchase reminder",
    "SMS credit purchase requires confirmation",
    "SMS Message",
    "Stripe receipt",
    "Subscription payment failure",
    "Today's appointments for practitioner",
    "Trial ending reminder",
    "Trial payment failure",
    "Unlock instructions",
    "Upcoming appointments",
    "Upcoming yearly payment alert",
    "User email changed",
    "User email confirmation instructions",
    "Xero OAuth error",
    "Xero sync error notification",
}


def check_email_communication_category(value: str) -> EmailCommunicationCategory:
    if value in EMAIL_COMMUNICATION_CATEGORY_VALUES:
        return cast(EmailCommunicationCategory, value)
    raise TypeError(f"Unexpected value {value!r}. Expected one of {EMAIL_COMMUNICATION_CATEGORY_VALUES!r}")
