from typing import Literal, Set, cast

TimeZone = Literal[
    "Abu Dhabi",
    "Adelaide",
    "Alaska",
    "Almaty",
    "American Samoa",
    "Amman",
    "Amsterdam",
    "Arizona",
    "Ashgabat",
    "Astana",
    "Asuncion",
    "Athens",
    "Atlantic Time (Canada)",
    "Auckland",
    "Azores",
    "Baghdad",
    "Baku",
    "Bangkok",
    "Beijing",
    "Beirut",
    "Belgrade",
    "Berlin",
    "Bern",
    "Bogota",
    "Brasilia",
    "Bratislava",
    "Brisbane",
    "Brussels",
    "Bucharest",
    "Budapest",
    "Buenos Aires",
    "Cairo",
    "Canberra",
    "Cape Verde Is.",
    "Caracas",
    "Casablanca",
    "Cayenne",
    "Central America",
    "Central Time (US & Canada)",
    "Chatham Is.",
    "Chennai",
    "Chihuahua",
    "Chongqing",
    "Copenhagen",
    "Damascus",
    "Darwin",
    "Dhaka",
    "Dublin",
    "Eastern Time (US & Canada)",
    "Edinburgh",
    "Ekaterinburg",
    "Fiji",
    "Georgetown",
    "Greenland",
    "Guadalajara",
    "Guam",
    "Hanoi",
    "Harare",
    "Hawaii",
    "Helsinki",
    "Hobart",
    "Hong Kong",
    "Indiana (East)",
    "International Date Line West",
    "Irkutsk",
    "Islamabad",
    "Istanbul",
    "Jakarta",
    "Jerusalem",
    "Kabul",
    "Kaliningrad",
    "Kamchatka",
    "Karachi",
    "Kathmandu",
    "Kolkata",
    "Krasnoyarsk",
    "Kuala Lumpur",
    "Kuwait",
    "Kyiv",
    "La Paz",
    "Lima",
    "Lisbon",
    "Ljubljana",
    "London",
    "Lord Howe",
    "Madrid",
    "Magadan",
    "Marshall Is.",
    "Mazatlan",
    "Melbourne",
    "Mexico City",
    "Mid-Atlantic",
    "Midway Island",
    "Minsk",
    "Monrovia",
    "Monterrey",
    "Montevideo",
    "Moscow",
    "Mountain Time (US & Canada)",
    "Mumbai",
    "Muscat",
    "Nairobi",
    "New Caledonia",
    "New Delhi",
    "Newfoundland",
    "Novosibirsk",
    "Nuku'alofa",
    "Osaka",
    "Oslo",
    "Pacific Time (US & Canada)",
    "Paris",
    "Perth",
    "Port Louis",
    "Port Moresby",
    "Prague",
    "Pretoria",
    "Puerto Rico",
    "Quito",
    "Rangoon",
    "Riga",
    "Riyadh",
    "Rome",
    "Samara",
    "Samoa",
    "Santiago",
    "Sapporo",
    "Sarajevo",
    "Saskatchewan",
    "Seoul",
    "Singapore",
    "Skopje",
    "Sofia",
    "Solomon Is.",
    "Srednekolymsk",
    "Sri Jayawardenepura",
    "St. Petersburg",
    "Stockholm",
    "Sydney",
    "Taipei",
    "Tallinn",
    "Tashkent",
    "Tbilisi",
    "Tehran",
    "Tijuana",
    "Tokelau Is.",
    "Tokyo",
    "Tripoli",
    "Ulaanbaatar",
    "Urumqi",
    "UTC",
    "Vienna",
    "Vilnius",
    "Vladivostok",
    "Volgograd",
    "Warsaw",
    "Wellington",
    "West Central Africa",
    "Windhoek",
    "Yakutsk",
    "Yerevan",
    "Zagreb",
    "Zurich",
]

TIME_ZONE_VALUES: Set[TimeZone] = {
    "Abu Dhabi",
    "Adelaide",
    "Alaska",
    "Almaty",
    "American Samoa",
    "Amman",
    "Amsterdam",
    "Arizona",
    "Ashgabat",
    "Astana",
    "Asuncion",
    "Athens",
    "Atlantic Time (Canada)",
    "Auckland",
    "Azores",
    "Baghdad",
    "Baku",
    "Bangkok",
    "Beijing",
    "Beirut",
    "Belgrade",
    "Berlin",
    "Bern",
    "Bogota",
    "Brasilia",
    "Bratislava",
    "Brisbane",
    "Brussels",
    "Bucharest",
    "Budapest",
    "Buenos Aires",
    "Cairo",
    "Canberra",
    "Cape Verde Is.",
    "Caracas",
    "Casablanca",
    "Cayenne",
    "Central America",
    "Central Time (US & Canada)",
    "Chatham Is.",
    "Chennai",
    "Chihuahua",
    "Chongqing",
    "Copenhagen",
    "Damascus",
    "Darwin",
    "Dhaka",
    "Dublin",
    "Eastern Time (US & Canada)",
    "Edinburgh",
    "Ekaterinburg",
    "Fiji",
    "Georgetown",
    "Greenland",
    "Guadalajara",
    "Guam",
    "Hanoi",
    "Harare",
    "Hawaii",
    "Helsinki",
    "Hobart",
    "Hong Kong",
    "Indiana (East)",
    "International Date Line West",
    "Irkutsk",
    "Islamabad",
    "Istanbul",
    "Jakarta",
    "Jerusalem",
    "Kabul",
    "Kaliningrad",
    "Kamchatka",
    "Karachi",
    "Kathmandu",
    "Kolkata",
    "Krasnoyarsk",
    "Kuala Lumpur",
    "Kuwait",
    "Kyiv",
    "La Paz",
    "Lima",
    "Lisbon",
    "Ljubljana",
    "London",
    "Lord Howe",
    "Madrid",
    "Magadan",
    "Marshall Is.",
    "Mazatlan",
    "Melbourne",
    "Mexico City",
    "Mid-Atlantic",
    "Midway Island",
    "Minsk",
    "Monrovia",
    "Monterrey",
    "Montevideo",
    "Moscow",
    "Mountain Time (US & Canada)",
    "Mumbai",
    "Muscat",
    "Nairobi",
    "New Caledonia",
    "New Delhi",
    "Newfoundland",
    "Novosibirsk",
    "Nuku'alofa",
    "Osaka",
    "Oslo",
    "Pacific Time (US & Canada)",
    "Paris",
    "Perth",
    "Port Louis",
    "Port Moresby",
    "Prague",
    "Pretoria",
    "Puerto Rico",
    "Quito",
    "Rangoon",
    "Riga",
    "Riyadh",
    "Rome",
    "Samara",
    "Samoa",
    "Santiago",
    "Sapporo",
    "Sarajevo",
    "Saskatchewan",
    "Seoul",
    "Singapore",
    "Skopje",
    "Sofia",
    "Solomon Is.",
    "Srednekolymsk",
    "Sri Jayawardenepura",
    "St. Petersburg",
    "Stockholm",
    "Sydney",
    "Taipei",
    "Tallinn",
    "Tashkent",
    "Tbilisi",
    "Tehran",
    "Tijuana",
    "Tokelau Is.",
    "Tokyo",
    "Tripoli",
    "Ulaanbaatar",
    "Urumqi",
    "UTC",
    "Vienna",
    "Vilnius",
    "Vladivostok",
    "Volgograd",
    "Warsaw",
    "Wellington",
    "West Central Africa",
    "Windhoek",
    "Yakutsk",
    "Yerevan",
    "Zagreb",
    "Zurich",
}


def check_time_zone(value: str) -> TimeZone:
    if value in TIME_ZONE_VALUES:
        return cast(TimeZone, value)
    raise TypeError(f"Unexpected value {value!r}. Expected one of {TIME_ZONE_VALUES!r}")
